<?php
namespace app\models;

use yii\db\ActiveRecord;
use yii\web\UploadedFile;

class FileUpload extends ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public $uploadFile;

    public function rules()
    {
        return [
            [['uploadFile'],
             'file',
             'skipOnEmpty' => false,
             'extensions' => 'mp4, avi, mkv, wmv, 3gp, png, jpg',
             'mimeTypes' => 'video/mp4, video/x-msvideo, video/3gpp, video/x-msvideo'
            ],
        ];
    }

    public function upload()
    {
        if ($this->validate()) {
           if ($this->uploadFile->extension == 'jpg' || $this->uploadFile->extension == 'png') {
               $uploadPath =   '/uploads/image/'.date('Ymd') . '/';
               $this->fileExists(dirname(__DIR__).'/web'.$uploadPath);
           } else {
               $uploadPath =   '/uploads/video/'.date('Ymd') . '/';
               $this->fileExists(dirname(__DIR__).'/web'.$uploadPath);
           }
           $uploadPath .= date('YmdHis') . rand(10000,99999) . '.' . $this->uploadFile->extension;
           $res = $this->uploadFile->saveAs(dirname(__DIR__).'/web'.$uploadPath);
//           var_dump($res,$uploadPath);exit;
           return 'https://dzongcn.net'.$uploadPath;
        } else {
            return false;
        }
    }

    public function fileExists($uploadpath)
    {
        if(!file_exists($uploadpath)){
            mkdir($uploadpath);
        }
        return $uploadpath;
    }

    /**
     * @param bool $insert
     * @return bool
     * @author wang
     */
    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}