<?php
/**
 * @package    http://www.rulaiyun.cn/
 * @author     wang <wangyaxu7019@dingtalk.com>
 * @copyright  Copyright &copy; rulaiyun.cn,2018 - 2019
 */

namespace backend\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "rly_wifi".
 *
 * @property int    $id
 * @property string $wifi_id               绑定无线网id
 * @property string $qrcode_path           二维码图片地址
 * @property string $create_time           创建时间
 * @property string $update_time           更新时间
 */
class Qrcode extends ActiveRecord
{
    public $times;
    public $user;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%qrcode}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'times',
                ],
                'required',
            ],
            [
                [
                    'times',
                ],
                'integer',
            ],
            [
                [
                    'user',
                    'SSID',
                ],
                'safe'
            ]

//            [
//                ['mobile'],
//                'match',
//                'pattern' => '/^1[34578]\d{9}$/',
//            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'wifi_id' => '绑定场所ID',
            'tiems' => '生成数量',
            'qrcode_path' => '图片地址',
            'create_time' => '创建日期',
            'update_time' => '更新日期',
        ];
    }



    public function getWifi()
    {
        return $this->hasOne(Wifi::className(),['id' => 'wifi_id']);
    }


    /**
     * @param bool $insert
     * @return bool
     * @author wang
     */
    public function beforeSave($insert)
    {
        if ($insert) {    //新增
            $this->create_time = date('Y-m-d H:i:s');
            $this->update_time = date('Y-m-d H:i:s');
        } else {    //修改
            $this->update_time = date('Y-m-d H:i:s');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool  $insert
     * @param array $changedAttributes
     * @author wang
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * 删除之后
     */
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }


}
